name: CI

on:
  push:
    branches:
      - master
      - beta
      - alpha
      - next
      - next-major
    tags-ignore:
      - "*"
    # do not trigger CI on tags, it will be handled by the release workflow
    paths:
      - "src/**"
      - "dist-tests/**"
      - package.json
      - pnpm-lock.yaml

  pull_request:
    branches:
      - master
      - beta
      - alpha
      - next
      - next-major
    paths:
      - "src/**"
      - "dist-tests/**"
      - package.json
      - pnpm-lock.yaml

jobs:
  call-test-workflow:
    # only run if we are NOT in a tag
    name: Call run-tests workflow
    # the linter may highlight this but it is correct
    uses: ./.github/workflows/run-tests.yml
