name: Release
on:
  push:
    branches:
      - master
      - beta
      - alpha
      - next
      - next-major
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      # See: https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: Get pnpm store directory
        shell: bash
        id: pnpm-store-path
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      # See: https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-store-path.outputs.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install

      # build before testing as some tests actually test the build
      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run dist tests
        run: pnpm test:dist

      - name: Semantic Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # we run docs:build twice because of the way the sidebar in vuepress plugin is generated
      - name: Deploy website
        run: |
          pnpm build:typedocs
          pnpm docs:build
          pnpm docs:build
          pnpm exec wrangler pages deploy docs/.vuepress/dist --branch ${{ github.ref_name }} --project-name caporal-website
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
